# Generated by Django 5.2.10 on 2026-02-24 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geofeature',
            name='geom_data',
        ),
        migrations.AddField(
            model_name='geofeature',
            name='geom',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='geofeature',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
